package main

func main() {
	// type_conversion()
	// helloWorld()
	// printConstantsAndVariables()
	// literal()
	// arithmetic()
	// relational()
	// logical()
	// bitwise()
	// hardbitwise()
	// assignment()
	// pointer()
	// iffunction()
	// hardiffunction()
	// switchs()
	// fors()
	// functions()
	// anonymous_functions()
	// closures()
	// arrays()
	// slices()
	// maps()
	// music_app()
	// external_modules()
	// structs()
	// methods()
	// interfaces()
	// errors()
	// defer_panic_recover()
	goroutines()
}
